const MIN_EMAIL_LENGTH = 3;
const MIN_PASSWORD_LENGTH = 6;
const MAX_POST_DESCRIPTION_LENGTH = 1024;
const MAX_POST_COMMENT_LENGTH = 256;

module.exports = {
    MIN_EMAIL_LENGTH,
    MIN_PASSWORD_LENGTH,
    MAX_POST_DESCRIPTION_LENGTH,
    MAX_POST_COMMENT_LENGTH
}